version: '3.8'

services:

  gomiddleman:
    build: .
    container_name: gomiddleman
    ports:
    - "8080:8080"
    restart: unless-stopped
    environment:
    - GOMIDDLEMAN_TARGET=http://localhost:3000
    - GOMIDDLEMAN_PORT=8080
    depends_on:
    - gomiddleman-nats
